### ISSUE TITLE
Font and Boss Key Bug

### ISSUE THREAD

**Issue by takaagry** [NelloKudo/osu-winello#115]
Hello, I just reinstall osu-winello with the newest version (15 hours ago as I write this) and found bugs.
The first one is the Boss Key (insert key by default) wont work so I cant hide osu.
The second one is the font on this version of osu-winello seems weird. 

I've checked on windows 11 that this is not happen both the Boss Key and the Font, so I think this not the issue from the osu (probably).

Below is screenshots of the font that seems weird in my opinion.

![screenshot001](https://github.com/user-attachments/assets/4f35b3f6-4cc0-4458-b8c8-c525f2cc1232)

![screenshot321](https://github.com/user-attachments/assets/9893008e-d652-42ba-a406-191c84f62ac4)

![screenshot318](https://github.com/user-attachments/assets/af4cef4c-e53f-4f4f-9dac-540a73101694)

screenshot001 or the first one is the screenshot I took from Windows 11
screenshot321 or the second one is the screenshot I took on Linux (EndeavourOS with KDE Plasma 6.2)
screenshot318 or the third one is the screenshot I took on Linux before this newest install (or before the crash yesterday)

Tbh I dont really mind about this bug, but I just hope this can be fixed if this somehow matter to anyone.

Note:
- The osu on Windows 11, I just fresh install it.
- The osu on Linux is fresh install of newest osu-winello, but then I replace the osu file with my older file (Skin, Song, config, database, ect)
- I've tried not replace the file on Linux and still got the same result

**Comment by takaagry** [comment]
Thank you for the answer. My bad and sorry I'm not reading the commit message before install the latest update. Hope this can be fixed soon.

**Comment by kartavkun** [comment]
maybe I am blind, but I don't see the difference xdd

**Comment by NelloKudo** [comment]
Readdressing the issue from last commit: 
------------------------------------------------------------------

When osu! detects it's running on Wine, it **forcefully changes** how fonts look and disables some features (like Boss key): we've already addressed ppy on the issue, hopefully it gets fixed soon.

In the meanwhile, for those who want the usual fonts look and features back, you can edit ~/.local/bin/osu-wine
and set `WINE_BLOCK_GET_VERSION` to 1, since we fixed Proton to work with it as well.
The only downside to that is that, with a future stable update, it might just break again: if that happens, please
revert it to 0 as it is the behavior osu! (and its devs) expect on Wine.

I'll just leave a simple command to make the switch to 1 for those who don't want to manually edit the file:
```
sed -i 's/WINE_BLOCK_GET_VERSION=0/WINE_BLOCK_GET_VERSION=1/' ~/.local/bin/osu-wine
```

Hopefully we'll have no need for this anymore soon!
