### ISSUE TITLE
Raw Input not capturing mouse (on wayland)

### ISSUE THREAD

**Issue by Anti-Apple4life** [NelloKudo/osu-winello#134]
When I enable raw input on the osu client, raw input is enabled, but the mouse moves out of the osu window, as the window is not capturing it.

**Comment by NelloKudo** [comment]
As he said, it's due to osu!'s behavior once it detects it's running under Wine, along with a bunch of other stuff.
You can read more at here: https://github.com/NelloKudo/osu-winello/issues/115#issuecomment-2466001112

For the time being, the fix is to set `WINE_BLOCK_GET_VERSION` to 1 so that the game detects it's on Windows and behaves normally. Revert to 0 if you notice any error with it!
