### ISSUE TITLE
Not having enough RAM causes extraction to fail

### ISSUE THREAD

**Issue by EllySensei** [NelloKudo/osu-winello#36]
OS: Arch Linux
RAM: 2gb
Both p7zip and tar cannot complete full extraction of their archives due to lacking enough RAM to store on /tmp
Consider adding an option if the end-user wants to extract directly to the specified directory or if they don't want to.

**Comment by Sclafus** [comment]
To be completely fair, with 2gb of ram probably you wouldn't be able to run the game... Have you considered adding a swap partition?

**Comment by EllySensei** [comment]
> To be completely fair, with 2gb of ram probably you wouldn't be able to run the game... Have you considered adding a swap partition?

I have in fact ran osu! Stable on 2gb of RAM on Linux. I also have an 8gb swap partition.
/tmp doesnt exactly make use of swap, that's why it fails, the wineprefix is gigabytes in size.

**Comment by Sclafus** [comment]
Agreed, it's running almost completely on ram since it is a ~200mb file.
The solution is doing a search and replace of `/tmp` with an arbitrary directory in [`osu-winello.sh`](https://github.com/NelloKudo/osu-winello/blob/main/osu-winello.sh) (and probably in [`osu-wine`](https://github.com/NelloKudo/osu-winello/blob/main/osu-wine#L293) as well)
I don't believe that this should be upstreamed, but it would be a good idea to have it configurable. @NelloKudo what do you think?

**Comment by Sclafus** [comment]
> Forgot to tell but apparently `/var/tmp`gets cleaned only after 30 days, and that might be a problem for those having such small memory on their systems.
> 
> Why don’t we just go with a random `~/.winellotmp` folder in $HOME and delete it as soon as the extraction is done? Probably the easiest way to get the trick done.

I think the current implementation is completely fine. We can add a parameter in the cli to specify where to download stuff.
like `osu-winello.sh --tempdir ~/.winello-tmp`

**Comment by NelloKudo** [comment]
Fixed in latest commit, ended up using the `~/.winellotmp` approach just to make things easier for users 👍🏻
