### ISSUE TITLE
wine prefix directory

### ISSUE THREAD

**Issue by VelamyGH** [NelloKudo/osu-winello#43]
it would be great if there was an option to choose the directory for osuwineprefix :) thanks

**Comment by NelloKudo** [comment]
Even though implementing it would probably be really easy, I pretty much prefer it to stay this way since the whole point behind it staying in`~/.local/share/wineprefixes ` is to make sure Winetricks can be used also with its GUI that would detect the prefix automatically.

If you need any help to actually move it tho I’m always willing to help! I’m still going to consider this for future updates if I can implement it in a way I do like as well ;)

**Comment by Sclafus** [comment]
Can be achieved with a symbolic link btw
