### ISSUE TITLE
rundll32.exe error upon launching osu!

### ISSUE THREAD

**Issue by NoelleTGS** [NelloKudo/osu-winello#45]
Since I first installed the script, launching osu! will occasionally pop up with this error.
![image](https://github.com/NelloKudo/osu-winello/assets/44215890/2a8b6330-cbbe-437a-8f62-c18a86676651)
As long as I press "No" the game seems to launch fine (after a bit of waiting), but I'm not sure why it happens or if there's a way to fix it.

**Comment by NelloKudo** [comment]
That happens during installs (and sometimes, when playing) whenever changes are made to prefix.

It indeed first happens during installation (where prefix is first initialized) and whenever you change the wine version you use to launch the game. This also includes launching the game from Lutris and then switching back to `osu-wine` xD

The reason this happens is just due to how `dotnet45` works with Wine, it does install properly and work but ends up prompting this random error sometimes for whatever reason. There's no way to fix it, you just need to ignore it 🏃🏻. If it bothers you, then make sure to always launch the game the same way!

Closing this but if you need any other explanation feel free to ask!! :)

**Comment by NoelleTGS** [comment]
Makes sense, as long as it won't cause any issues then we're all good :)
