### ISSUE TITLE
When importing a beatmap game crashes

### ISSUE THREAD

**Issue by Michy234** [NelloKudo/osu-winello#58]
Hello there, i've been using osu-winello for a long time now; for a month now i've been encountering this problem that consists in this: everytime i open osu! for the first time in my game session and try to import a beatmap, the game freezes and the audio continues playing. I need to kill the process and then only after i reboot osu! i can import that beatmap. My system runs EndeavourOS Galileo, kernel 6.6.4-arch1-1, KDE, AMD GPU. What could be the problem?

**Comment by NelloKudo** [comment]
_bella foto bro hevrnsajsvedhhewhaha_

The issue with it is a test within Wine, which crashes on the first load but works on the second for whatever reason. And yeah, it can be disabled when building, _but I totally forgot to ever since I stopped having the same problem 💀_

Gonna upload a build for you later and write what to do, if it works then I’m switching the script to it as well!

**Comment by NelloKudo** [comment]
Also just to make sure that’s it, could you run `osu-wine` in your terminal and send a screenshot of the logs when it crashes?

**Comment by NelloKudo** [comment]
Should be fixed in https://github.com/NelloKudo/osu-winello/commit/310ddebb28348874f854d1d01c1e7b437a673b82, please run `osu-wine --update` and see if the crash still happens 🙏
