### ISSUE TITLE
"Your version of osu! is too old to submit scores" on an up-to-date installation

### ISSUE THREAD

**Issue by Inconn** [NelloKudo/osu-winello#8]
I can't submit scores because apparently my osu! is too old. However whenever I start the game the updater says that osu is up-to-date. This issue started seemingly out of no-where, my last submitted score was 18 hours ago and it worked fine, but out of nowhere I was just unable to submit scores. It started on stable but I switched to cutting-edge and the issue stayed.
There are two other people that say they've had the issue in the osu-wine thread and apparently one person solved it by updating osu-wine and updating their system, but that didn't work for me.

Distro: Ubuntu 22.04.1
Kernel: 5.15.0-43-generic
Using NVIDIA's proprietary 515 drivers with 32 bit binaries installed

What I have tried:
- Switching to cutting-edge
- Running `osu-wine --update`
- Running `sudo apt-get update && sudo apt-get upgrade` and rebooting
- Running `osu-wine --fixprefix`
- Not using gamemoderun to start osu.

**Comment by NelloKudo** [comment]
Fixed in https://github.com/NelloKudo/osu-winello/commit/5d6454a4b9f1e0f90a82087b00c4eb9122bdd4b2, it is an error related to the latest osu! update and not to wine/script in any way.

The fix is to edit `~/.local/bin/osu-wine` and delete the line with `WINE_BLOCK_GET_VERSION=1`, for example using nano:

`nano ~/.local/bin/osu-wine` and deleting that line, then saving with CTRL+O

**Comment by Inconn** [comment]
Thanks, you should probably put an update that pushes this, (or if u have, i guess my osu-wine didn't get the memo)

**Comment by NelloKudo** [comment]
Yeah, I need to figure a way to implement such fixes in the future. Thank you for reporting! I also wrote a post on the forum :3
